### ISSUE TITLE
Old version of AWS-SDK

### ISSUE THREAD

**Issue by matthew-andrews** [yegor256/dynamo-archive#21]
Is there any reason why this module is tied to an old version of the AWS-SDK?

I've only tested the archiving functionality (not the restoring) but it seems to work OK.

Current version: 2.2.33
Semver range for dynamo-archive: 2.0.x

**Comment by yegor256** [comment]
@matthew-andrews there is no reason. feel free to submit a pull request with an upgrade

**Comment by davvd** [comment]
@rultor @matthew-andrews please take a look, rultor closed it automatically

**Comment by matthew-andrews** [comment]
i think it was right to close this? @davvd
