### ISSUE TITLE
aws iam role

### ISSUE THREAD

**Issue by cristiansavaro** [yegor256/dynamo-archive#23]
could you please implement the same mechanism that aws cli employs in order to retrieve and use temporary credentials assigned to the instance by use of iam roles (key, secret, token) ?

here's an example output : 

`curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/iam-role-name`

```
{
  "Code" : "Success",
  "LastUpdated" : "2016-02-07T07:54:27Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "ASIAXXXXXXXXXXXXXXXXXXXX",
  "SecretAccessKey" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "Token" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==",
  "Expiration" : "2016-02-07T14:16:27Z"
}
```

this way we can all use your tool in complex automatic deployment scenarios that make use of aws cloudformation without embedding credentials in any script...which i think is very useful as a new feature.

**Comment by cristiansavaro** [comment]
this way i can make use of your tool in complex automatic deployment scenarios that make use of aws cloudformation without embedding credentials in any script...which i think is very useful for everyone.

**Comment by yegor256** [comment]
@cristiansavaro I think that if you just don't provide any credentials, they will be retrieved automatically from the instance... try it.

**Comment by cristiansavaro** [comment]
@yegor256 key and secret yes, token no (or doesn't know how to use it).
i have tried it with a few roles. it fails on authentication and i made sure i had administrative access level to the roles for dynamodb.

**Comment by rozhok** [comment]
@cristiansavaro could you show your instance profile? If your regular app works fine than script should also work fine.

**Comment by cristiansavaro** [comment]
there was an issue on my side which prevented normal functioning.
