### ISSUE TITLE
How about incremental backups/restores?

### ISSUE THREAD

**Issue by rozhok** [yegor256/dynamo-archive#25]
This script is useless for large tables with gazillions of records, it would be nice to have a incremental backups and restores. There is already solutions like https://github.com/mapbox/dynamodb-replicator but it's not well documented and requires some other tools for deployment.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@rozhok why it's useless? what is your use case?

**Comment by rozhok** [comment]
@yegor256 Sorry, misunderstood this tool concepts.
I'll close the issue.
